import Image from 'next/image'
import Link from 'next/link'
import { ArrowDownRight } from 'lucide-react'
import { catalog,projects } from '@/lib/content'
import { Eyebrow,Footer,Header,TextLink } from '@/components/site-shell'
import { InquiryForm } from '@/components/inquiry-form'
const heroMedia:Record<string,string>={'0247':'0235','0077':'0236','0229':'0233','0087':'0175','0150':'0234','0249':'0236'}
const img=(n:string)=>`/images/IMG-20260813-WA${heroMedia[n]||n}.jpg`
export default function Home(){return <main className="page-enter"><Header/><section className="hero"><Image src={img('0247')} alt="A finished Woodwey interior with custom furniture" fill priority className="object-cover" sizes="100vw"/><div className="hero-shade"/><div className="shell relative flex min-h-[92svh] flex-col justify-end pb-10 pt-28 text-ivory md:pb-14"><p className="hero-kicker">Furniture & interior solutions · Made in Nigeria</p><div className="mt-5 grid gap-8 md:grid-cols-[1fr_auto] md:items-end"><h1>Built for the spaces<br className="hidden md:block"/> that matter.</h1><div className="grid min-w-56 gap-3"><TextLink href="/projects">Explore our work</TextLink><TextLink href="#contact">Start a project</TextLink></div></div><ArrowDownRight className="mt-8 text-orange"/></div></section>
<section id="about" className="section subtle-grid"><div className="shell"><Eyebrow>About Woodwey</Eyebrow><div className="grid gap-12 lg:grid-cols-12"><div className="lg:col-span-7"><h2 className="display">Built in Nigeria. <span>Designed for the way spaces are lived in.</span></h2><div className="editorial-pair mt-12"><Image src={img('0077')} alt="Finished residential space by Woodwey" width={1200} height={1500} className="aspect-[4/5] object-cover"/><Image src={img('0106')} alt="Woodwey furniture detail" width={900} height={700} className="aspect-[4/3] object-cover"/></div></div><div className="flex flex-col justify-end gap-6 lg:col-span-4 lg:col-start-9"><p className="body-lg">Woodwey is a Lagos-based furniture studio creating custom pieces and complete interior solutions for homes, offices, schools, banks and commercial spaces.</p><p className="text-muted-foreground leading-relaxed">Design, fabrication and installation come together under one roof. From a singular chair or executive desk to a fully furnished interior, each project is shaped around function, material and the people who will use it. Proudly made in Nigeria by craftspeople who understand how beautiful spaces must also work.</p><TextLink href="/catalog">Explore what we make</TextLink></div></div></div></section>
<section className="section bg-ink text-ivory"><div className="shell"><Eyebrow>Selected work</Eyebrow><div className="flex items-end justify-between"><h2 className="display max-w-4xl">Spaces with a point of view.</h2><TextLink href="/projects">View all work</TextLink></div><div className="selected-grid mt-14">{projects.map((p,i)=><Link href="/projects" key={p.name} className={`group selected-${i+1}`}><div className="media-hover relative h-full min-h-80 overflow-hidden"><Image src={p.image} alt={p.alt} fill className="object-cover" sizes="(min-width:768px) 50vw,100vw"/><span className="media-caption">Discover project</span></div><div className="mt-3 flex justify-between"><h3 className="font-serif text-2xl">{p.name}</h3><p className="text-[10px] uppercase tracking-[.18em] text-ivory/50">{p.category}</p></div></Link>)}</div></div></section>
<section className="section bg-sand"><div className="shell"><div className="grid gap-8 md:grid-cols-2 md:items-end"><div><Eyebrow>Object of interest</Eyebrow><h2 className="display">The detail makes the piece.</h2></div><p className="max-w-md text-muted-foreground md:justify-self-end">A closer look at forms, textures and furniture made for a particular place.</p></div><div className="object-strip no-scrollbar mt-12">{catalog.slice(0,5).map(item=><Link href="/catalog" key={item.id} className="group"><div className="media-hover relative aspect-[3/4] overflow-hidden"><Image src={item.image} alt={item.alt} fill className="object-cover" sizes="(min-width:900px) 25vw,75vw"/></div><h3 className="mt-3 font-serif text-2xl">{item.name}</h3><p className="text-xs text-muted-foreground">{item.category}</p></Link>)}</div></div></section>
<section className="section"><div className="shell"><Eyebrow>How we work</Eyebrow><div className="process-grid">{[['01','Listen','We understand the space, its people and the ambition behind it.','0229'],['02','Make','Design and fabrication develop closely, with care in every junction.','0087'],['03','Install','We bring every element together and leave the space ready for life.','0150']].map(([n,t,d,x])=><article key={n} className="process-card"><div className="relative aspect-[4/5] overflow-hidden"><Image src={img(x)} alt={`${t} stage of the Woodwey process`} fill className="object-cover transition duration-700 hover:scale-[1.025]"/></div><span>{n}</span><h3>{t}</h3><p>{d}</p></article>)}</div></div></section>
<section id="contact" className="contact-section"><Image src={img('0249')} alt="" fill className="object-cover opacity-20"/><div className="shell relative grid gap-14 lg:grid-cols-2"><div><Eyebrow>Have a space in mind?</Eyebrow><h2 className="display max-w-xl">Let&apos;s make something worth keeping.</h2><p className="mt-7 max-w-md text-ink/65">Tell us what the space needs to become. Add references from the catalog or photos of the room, and we will take it from there.</p></div><InquiryForm/></div></section><Footer/></main>}
