import Image from 'next/image'
import Link from 'next/link'
import { ArrowDown, ArrowUpRight } from 'lucide-react'
import { BackgroundMotif } from '@/components/background-motif'
import { Footer, Header, ButtonLink, Eyebrow } from '@/components/site-shell'
import { InquiryForm } from '@/components/inquiry-form'
import { HeroTerms } from '@/components/hero-terms'

const image=(n:string)=>`/images/IMG-20260813-WA${n}.jpg`
const collections=[
  {name:'Home',copy:'Furniture for living well.',image:'0165'},
  {name:'Office',copy:'A more composed work day.',image:'0134'},
  {name:'Interiors',copy:'Designed around the space.',image:'0146'},
  {name:'Metal Works',copy:'Architectural structure and detail.',image:'0059'},
]
const aboutImages=[
  ['0137','Warm timber furniture detail'],['0006','Timber media console in a finished living room'],['0196','Custom bedroom storage'],['0146','Architectural media wall'],
  ['0208','Contemporary office installation'],['0059','Wide custom metal entrance gate'],['0151','Bespoke boardroom furniture'],['0183','Custom collaborative table'],['0165','Woodwey upholstered living room furniture'],
]

export default function Home(){return <main className="page-enter"><Header/>
  <section className="hero" data-protected-media><Image src={image('0234')} alt="A finished Woodwey corporate interior in warm timber" fill loading="eager" fetchPriority="high" draggable={false} className="object-cover" sizes="100vw"/><div className="hero-shade"/><BackgroundMotif className="hero-motif"/><div className="shell hero-layout"><div className="hero-copy"><p className="hero-kicker">Woodwey · Lagos, Nigeria</p><HeroTerms/><p className="hero-intro hero-intro-reveal">Custom furniture, interiors and metalworks — made in Lagos</p></div><Link href="/catalog" className="hero-discovery"><span>Explore the Collection</span><ArrowUpRight/></Link><a href="#what-we-create" aria-label="Scroll to what we create" className="hero-scroll"><ArrowDown/></a></div></section>

  <section id="what-we-create" className="section collection-section"><div className="shell"><div className="section-heading"><div><Eyebrow>What we create</Eyebrow><h2 className="display">Every space considered.</h2></div></div><div className="collection-grid">{collections.map((item,index)=><Link href={`/catalog?category=${encodeURIComponent(item.name)}`} className="collection-card protected-media" data-protected-media key={item.name}><Image src={image(item.image)} alt={`${item.name} by Woodwey`} fill draggable={false} className="object-cover" sizes="(min-width:900px) 25vw,82vw"/><span className="media-watermark wm-a" aria-hidden="true">WOODWEY</span><span className="collection-overlay"/><small>0{index+1}</small><div><h3>{item.name}</h3><p>{item.copy}</p><span>Discover <ArrowUpRight size={15}/></span></div></Link>)}</div></div></section>

  <section id="about" className="section about-section"><BackgroundMotif variant="joinery" className="about-motif"/><div className="shell"><div className="about-lead"><h2 className="display">Made here.<br/><span>Designed to belong anywhere.</span></h2><div className="button-row"><ButtonLink href="/projects">View our work</ButtonLink></div></div><div className="about-collage">{aboutImages.map(([src,alt],index)=><div key={src} className={`about-image about-image-${index+1} protected-media wm-${String.fromCharCode(97+(index%4))}`} data-protected-media><Image src={image(src)} alt={alt} fill draggable={false} className="object-cover" sizes="(min-width:1200px) 28vw,(min-width:700px) 44vw,48vw"/><span className="media-watermark" aria-hidden="true">WOODWEY</span></div>)}</div></div></section>

  <section className="section capabilities-section"><BackgroundMotif variant="metal" className="capabilities-motif"/><div className="shell"><div className="capabilities-head"><div><Eyebrow>Furniture & Metal Works</Eyebrow><h2 className="display">One workshop.<br/><span>Complete spaces.</span></h2></div><p>Wood and metal developed together for better control of form, finish and installation.</p></div><div className="capabilities-layout"><div className="capabilities-list">{[
    ['01','Furniture','Custom pieces, fitted storage and workspace systems.'],
    ['02','Interiors','Materials, furniture and installation resolved as one.'],
    ['03','Metal Works','Architectural gates and fabricated elements made precisely.'],
  ].map(([number,title,copy])=><article key={number}><span>{number}</span><div><h3>{title}</h3><p>{copy}</p></div></article>)}</div><div className="metal-collage"><div className="metal-image metal-image-main protected-media wm-c" data-protected-media><Image src={image('0059')} alt="Wide modern entrance gate fabricated by Woodwey" fill draggable={false} className="object-cover" sizes="(min-width:900px) 48vw,100vw"/><span className="media-watermark" aria-hidden="true">WOODWEY</span></div><div className="metal-image metal-image-top protected-media wm-a" data-protected-media><Image src={image('0055')} alt="Finished louvred metal entrance gate" fill draggable={false} className="object-cover" sizes="(min-width:900px) 22vw,45vw"/><span className="media-watermark" aria-hidden="true">WOODWEY</span></div><div className="metal-image metal-image-bottom protected-media wm-d" data-protected-media><Image src={image('0072')} alt="Finished ribbed sliding gate" fill draggable={false} className="object-cover" sizes="(min-width:900px) 22vw,45vw"/><span className="media-watermark" aria-hidden="true">WOODWEY</span></div></div></div><div className="capabilities-action"><ButtonLink href="/catalog?category=Metal%20Works" tone="light">Explore Metal Works</ButtonLink></div></div></section>

  <section className="section process-section"><div className="shell"><Eyebrow>How we work</Eyebrow><div className="process-intro"><h2 className="display">One Team<br/><span>from BRIEF to ROOM</span></h2><p>Design, manufacturing and installation remain connected.</p></div><div className="process-grid">{[['01','Listen','Understand the space, needs and intent.','/downloads/Listen-full.jpg'],['02','Make','Craft the furniture, interiors and metalwork.','/downloads/Make-full.png'],['03','Install','Bring the finished work into place.',image('0166')]].map(([number,title,copy,media],index)=><article className="process-card" key={number}><div className={`process-media protected-media wm-${String.fromCharCode(97+index)}`} data-protected-media><Image src={media} alt={`${title}: ${copy}`} fill draggable={false} className="object-cover" sizes="(min-width:900px) 33vw,100vw"/><span className="media-watermark" aria-hidden="true">WOODWEY</span></div><div><span>{number}</span><h3>{title}</h3><p>{copy}</p></div></article>)}</div></div></section>

  <section className="section director-section"><BackgroundMotif variant="joinery" className="director-motif"/><div className="shell"><Eyebrow>About us</Eyebrow><div className="director-layout"><div className="director-placeholder" role="img" aria-label="Temporary placeholder for the Woodwey director portrait"><span>WOODWEY</span><p>Director portrait<br/>coming soon</p></div><div className="director-copy"><h2 className="display">Meet the Director</h2><p>Director profile coming soon. This space will introduce the person behind Woodwey and the vision guiding its furniture, interiors and metalwork.</p><p>Portrait and final story to be added by Woodwey.</p></div></div></div></section>
  <section id="contact" className="contact-section"><div className="contact-atmosphere"/><div className="shell contact-layout"><div className="contact-copy"><Eyebrow>Begin a project</Eyebrow><h2 className="display">Tell us about<br/>your space.</h2><p>Share the essentials. We will take it from there.</p><div className="contact-note"><span>Prefer email?</span><a href="mailto:hello@woodweyng.com">hello@woodweyng.com</a></div></div><InquiryForm/></div></section><Footer/>
  </main>}
