import Image from 'next/image'
import Link from 'next/link'
import { ArrowDown, ArrowUpRight } from 'lucide-react'
import { BackgroundMotif } from '@/components/background-motif'
import { Footer, Header, ButtonLink, Eyebrow } from '@/components/site-shell'
import { InquiryForm } from '@/components/inquiry-form'

const image=(n:string)=>`/images/IMG-20260813-WA${n}.jpg`
const collections=[
  {name:'Home',copy:'Furniture for living well.',image:'0162'},
  {name:'Office',copy:'A more composed work day.',image:'0134'},
  {name:'Interiors',copy:'Designed around the space.',image:'0146'},
  {name:'Metal Works',copy:'Architectural structure and detail.',image:'0059'},
]
const aboutImages=[
  ['0137','Warm timber furniture detail'],['0162','Finished dining furniture'],['0196','Custom bedroom storage'],['0146','Architectural media wall'],
  ['0208','Contemporary office installation'],['0059','Wide custom metal entrance gate'],['0151','Bespoke boardroom furniture'],['0183','Custom collaborative table'],
]

export default function Home(){return <main className="page-enter"><Header/>
  <section className="hero" data-protected-media><Image src={image('0234')} alt="A finished Woodwey corporate interior in warm timber" fill priority draggable={false} className="object-cover" sizes="100vw"/><div className="media-watermark wm-b" aria-hidden="true">WOODWEY</div><div className="hero-shade"/><BackgroundMotif className="hero-motif"/><div className="shell hero-layout"><div className="hero-copy"><p className="hero-kicker">Woodwey · Lagos, Nigeria</p><h1>Furniture and interiors.<br/>{' '}<em>Made to belong.</em></h1><p className="hero-intro">Custom furniture, complete interiors and architectural metalwork—designed and made in Nigeria.</p><p className="hero-services">Furniture <i/> Interiors <i/> Metal Works</p><div className="hero-actions"><ButtonLink href="/projects">Explore our work</ButtonLink><ButtonLink href="#contact" tone="light">Start a project</ButtonLink></div></div><Link href="/catalog" className="hero-discovery"><span>Explore the collection</span><strong>Furniture made<br/>for your space.</strong><ArrowUpRight/></Link><a href="#what-we-create" aria-label="Scroll to what we create" className="hero-scroll"><ArrowDown/></a></div></section>

  <section id="what-we-create" className="section collection-section"><div className="shell"><div className="section-heading"><div><Eyebrow>What we create</Eyebrow><h2 className="display">Spaces, considered<br/>from every angle.</h2></div><p>Furniture, interiors and metalwork shaped as one complete response.</p></div><div className="collection-grid">{collections.map((item,index)=><Link href={`/catalog?category=${encodeURIComponent(item.name)}`} className="collection-card protected-media" data-protected-media key={item.name}><Image src={image(item.image)} alt={`${item.name} by Woodwey`} fill draggable={false} className="object-cover" sizes="(min-width:900px) 25vw,82vw"/><span className="media-watermark wm-a" aria-hidden="true">WOODWEY</span><span className="collection-overlay"/><small>0{index+1}</small><div><h3>{item.name}</h3><p>{item.copy}</p><span>Discover <ArrowUpRight size={15}/></span></div></Link>)}</div></div></section>

  <section id="about" className="section about-section"><BackgroundMotif variant="joinery" className="about-motif"/><div className="shell"><div className="about-lead"><Eyebrow>About Woodwey</Eyebrow><h2 className="display">Made here.<br/><span>Designed to belong anywhere.</span></h2><div><p className="body-lg">A Lagos-based company creating custom furniture, architectural metalwork and interior solutions for the places where people live, work, learn and gather.</p><p>Design, fabrication and installation stay connected from first idea to finished space.</p><div className="button-row"><ButtonLink href="/projects">View our work</ButtonLink><ButtonLink href="/catalog" variant="outline">Explore collection</ButtonLink></div></div></div><div className="about-collage">{aboutImages.map(([src,alt],index)=><div key={src} className={`about-image about-image-${index+1} protected-media wm-${String.fromCharCode(97+(index%4))}`} data-protected-media><Image src={image(src)} alt={alt} fill draggable={false} className="object-cover" sizes="(min-width:1200px) 28vw,(min-width:700px) 44vw,48vw"/><span className="media-watermark" aria-hidden="true">WOODWEY</span></div>)}</div></div></section>

  <section className="section capabilities-section"><BackgroundMotif variant="metal" className="capabilities-motif"/><div className="shell"><div className="capabilities-head"><div><Eyebrow>Furniture & Metal Works</Eyebrow><h2 className="display">One workshop.<br/><span>Complete spaces.</span></h2></div><p>Wood and metal developed together for better control of form, finish and installation.</p></div><div className="capabilities-layout"><div className="capabilities-list">{[
    ['01','Furniture','Custom pieces, fitted storage and workspace systems.'],
    ['02','Interiors','Materials, furniture and installation resolved as one.'],
    ['03','Metal Works','Architectural gates and fabricated elements made precisely.'],
  ].map(([number,title,copy])=><article key={number}><span>{number}</span><div><h3>{title}</h3><p>{copy}</p></div></article>)}</div><div className="metal-collage"><div className="metal-image metal-image-main protected-media wm-c" data-protected-media><Image src={image('0059')} alt="Wide modern entrance gate fabricated by Woodwey" fill draggable={false} className="object-cover" sizes="(min-width:900px) 48vw,100vw"/><span className="media-watermark" aria-hidden="true">WOODWEY</span></div><div className="metal-image metal-image-top protected-media wm-a" data-protected-media><Image src={image('0055')} alt="Finished louvred metal entrance gate" fill draggable={false} className="object-cover" sizes="(min-width:900px) 22vw,45vw"/><span className="media-watermark" aria-hidden="true">WOODWEY</span></div><div className="metal-image metal-image-bottom protected-media wm-d" data-protected-media><Image src={image('0072')} alt="Finished ribbed sliding gate" fill draggable={false} className="object-cover" sizes="(min-width:900px) 22vw,45vw"/><span className="media-watermark" aria-hidden="true">WOODWEY</span></div></div></div><div className="capabilities-action"><ButtonLink href="/catalog?category=Metal%20Works" tone="light">Explore Metal Works</ButtonLink></div></div></section>

  <section className="section process-section"><div className="shell"><Eyebrow>How we work</Eyebrow><div className="process-intro"><h2 className="display">One team.<br/><span>From brief to room.</span></h2><p>Design, manufacturing and installation remain connected.</p></div><div className="process-grid">{[['01','Listen','Understand the space, needs and intent.','0233'],['02','Make','Craft the furniture, interiors and metalwork.','0166'],['03','Install','Bring the finished work into place.','0208']].map(([number,title,copy,media],index)=><article className="process-card" key={number}><div className={`process-media protected-media wm-${String.fromCharCode(97+index)}`} data-protected-media><Image src={image(media)} alt={`${title}: ${copy}`} fill draggable={false} className="object-cover" sizes="(min-width:900px) 33vw,100vw"/><span className="media-watermark" aria-hidden="true">WOODWEY</span></div><div><span>{number}</span><h3>{title}</h3><p>{copy}</p></div></article>)}</div></div></section>

  <section id="contact" className="contact-section"><div className="contact-atmosphere"/><div className="shell contact-layout"><div className="contact-copy"><Eyebrow>Begin a project</Eyebrow><h2 className="display">Tell us about<br/>your space.</h2><p>Share the essentials. We will take it from there.</p><div className="contact-note"><span>Prefer email?</span><a href="mailto:hello@woodweyng.com">hello@woodweyng.com</a></div></div><InquiryForm/></div></section><Footer/>
  </main>}
