'use client'
import Image from 'next/image'
import { useEffect,useMemo,useRef,useState } from 'react'
import { ArrowLeft,ArrowRight,ArrowUpRight,Check,LoaderCircle,Upload,X } from 'lucide-react'
import { catalog } from '@/lib/content'
import { useSelection } from '@/lib/selection'

const spaces=['Home','Office','Dining','Bedroom','School','Commercial','Hospitality','Exterior / Entry','Full Interior','Other']
const needs=['Sofas','Chairs','Tables','Dining Furniture','TV Console','Workstations','Worktops','Office Furniture','Bedroom Furniture','Storage','Interior Design','Full Space','Custom Furniture','Metal Works','Gates / Metal Screens','Other']
type Details={name:string;email:string;phone:string;space:string;need:string;details:string}
const initial:Details={name:'',email:'',phone:'',space:'',need:'',details:''}

export function InquiryForm(){
 const[step,setStep]=useState(0);const[values,setValues]=useState(initial);const[files,setFiles]=useState<File[]>([]);const[status,setStatus]=useState<'idle'|'loading'|'success'|'error'>('idle');const[message,setMessage]=useState('');const[fallback,setFallback]=useState('');const input=useRef<HTMLInputElement>(null);const replaceIndex=useRef<number|null>(null);const selected=useSelection();
 const previews=useMemo(()=>files.map(file=>({file,url:URL.createObjectURL(file)})),[files]);useEffect(()=>()=>previews.forEach(x=>URL.revokeObjectURL(x.url)),[previews]);
 const update=(key:keyof Details,value:string)=>{setValues(v=>({...v,[key]:value}));setMessage('')};
 const valid=()=>{if(step===0&&(!values.name.trim()||!/^\S+@\S+\.\S+$/.test(values.email)||!values.phone.trim()))return 'Complete your name, a valid email and phone number.';if(step===1&&!values.space)return 'Choose the kind of space you are working on.';if(step===2&&!values.need)return 'Choose what you are looking for.';if(step===3&&!values.details.trim())return 'Tell us a little about the project.';return ''};
 const next=()=>{const error=valid();if(error){setMessage(error);setStatus('error');return}setStatus('idle');setMessage('');setStep(s=>Math.min(4,s+1))};
 const choose=(list:FileList|null,replace?:number)=>{if(!list?.length)return;const good=[...list].filter(f=>/^image\/(jpeg|png|webp)$/.test(f.type)&&f.size<=5*1024*1024);if(!good.length){setMessage('Use JPG, PNG or WebP images under 5 MB.');setStatus('error');return}setFiles(current=>replace===undefined?[...current,...good].slice(0,5):current.map((f,i)=>i===replace?good[0]:f));setStatus('idle');setMessage('')};
 const submit=async()=>{setStatus('loading');setMessage('');setFallback('');const data=new FormData();Object.entries(values).forEach(([key,value])=>data.set(key,value));files.forEach(file=>data.append('photos',file));const names=selected.map(id=>catalog.find(item=>item.id===id)?.name).filter(Boolean).join(', ');data.set('selection',names);try{const response=await fetch('/api/inquiry',{method:'POST',body:data});const result=await response.json();if(!response.ok){if(response.status===503){const text=[`Hello Woodwey, I would like to discuss a project.`,`Name: ${values.name}`,`Space: ${values.space}`,`Looking for: ${values.need}`,names&&`Selected references: ${names}`,`Details: ${values.details}`].filter(Boolean).join('\n');setFallback(`https://wa.me/2348032973402?text=${encodeURIComponent(text)}`)}throw new Error(result.error||'Unable to send your request.')}setValues(initial);setFiles([]);setStep(0);setStatus('success');setMessage(result.message)}catch(error){setStatus('error');setMessage(error instanceof Error?error.message:'Unable to send your request.')}};
 return <form className="inquiry-form" onSubmit={event=>{event.preventDefault();if(step===4&&status!=='loading')void submit()}} noValidate><div className="form-head"><div><span>Project enquiry</span><strong>Step {step+1} of 5</strong></div><div className="form-progress" aria-label={`Step ${step+1} of 5`}>{[0,1,2,3,4].map(i=><i key={i} className={i<=step?'active':''}/>)}</div></div><div className="form-stage" key={step}>
 {step===0&&<><h3>First, how can we reach you?</h3><div className="field-grid"><Field label="Name"><input value={values.name} onChange={e=>update('name',e.target.value)} autoComplete="name" required/></Field><Field label="Email"><input value={values.email} onChange={e=>update('email',e.target.value)} type="email" autoComplete="email" required/></Field></div><Field label="Phone / WhatsApp"><input value={values.phone} onChange={e=>update('phone',e.target.value)} type="tel" autoComplete="tel" required/></Field></>}
 {step===1&&<><h3>What is your space like?</h3><p className="form-hint">Choose the closest match. We can refine the details together.</p><div className="choice-grid">{spaces.map(x=><button type="button" className={values.space===x?'active':''} onClick={()=>update('space',x)} key={x}>{x}{values.space===x&&<Check/>}</button>)}</div></>}
 {step===2&&<><h3>What are you looking for?</h3><p className="form-hint">Select the main requirement for this enquiry.</p><div className="choice-grid">{needs.map(x=><button type="button" className={values.need===x?'active':''} onClick={()=>update('need',x)} key={x}>{x}{values.need===x&&<Check/>}</button>)}</div></>}
 {step===3&&<><h3>Tell us about the project.</h3><Field label="Your brief"><textarea value={values.details} onChange={e=>update('details',e.target.value)} rows={7} required placeholder="Share dimensions, quantities, style, timeline and budget if you wish."/></Field></>}
 {step===4&&<><h3>Add visual references.</h3><p className="form-hint">Optional. Upload up to five JPG, PNG or WebP images, no more than 5 MB each.</p><button className="upload-button" type="button" onClick={()=>{replaceIndex.current=null;input.current?.click()}}><Upload/>Choose images</button><input ref={input} className="sr-only" type="file" accept="image/jpeg,image/png,image/webp" multiple onChange={e=>{choose(e.target.files,replaceIndex.current??undefined);replaceIndex.current=null;e.target.value=''}}/>{previews.length>0&&<div className="upload-previews">{previews.map(({file,url},i)=><div key={`${file.name}-${i}`}><Image src={url} alt={`Upload preview ${i+1}`} fill className="object-cover" unoptimized/><button type="button" onClick={()=>setFiles(v=>v.filter((_,n)=>n!==i))} aria-label={`Remove ${file.name}`}><X/></button><button type="button" className="replace" onClick={()=>{replaceIndex.current=i;input.current?.click()}}>Replace</button></div>)}</div>}{selected.length>0&&<div className="form-selection"><span>Your catalogue selection</span><strong>{selected.length} item{selected.length===1?'':'s'} included</strong></div>}</>}
 </div>{message&&<p role="status" className={`form-message ${status==='error'?'error':''}`}>{message}</p>}{fallback&&<a className="form-fallback" href={fallback} target="_blank" rel="noreferrer">Continue on WhatsApp <ArrowUpRight/></a>}<div className="form-actions">{step>0?<button type="button" className="form-back" onClick={()=>{setStep(s=>s-1);setMessage('')}}><ArrowLeft/>Back</button>:<span/>}{step<4?<button key="continue" type="button" className="form-next" onClick={event=>{event.preventDefault();next()}}>Continue<ArrowRight/></button>:<button key="submit" type="button" onClick={()=>void submit()} className="form-next" disabled={status==='loading'}>{status==='loading'?<><LoaderCircle className="spin"/>Sending</>:<>Send enquiry<ArrowUpRight/></>}</button>}</div></form>}

function Field({label,children}:{label:string;children:React.ReactNode}){return <label className="form-label"><span>{label}</span>{children}</label>}
