'use client'
import Image from 'next/image'
import Link from 'next/link'
import { useCallback,useEffect,useMemo,useState } from 'react'
import { createPortal } from 'react-dom'
import { ArrowLeft,ArrowRight,ArrowUpRight,Play,X } from 'lucide-react'
import { projectCategories,projectMedia,type MediaItem } from '@/lib/content'
import { SmartVideo } from './smart-video'

export function ProjectsExperience(){const[category,setCategory]=useState<(typeof projectCategories)[number]>('All');const[limit,setLimit]=useState(12);const[active,setActive]=useState<MediaItem|null>(null);const filtered=useMemo(()=>projectMedia.filter(item=>category==='All'||item.category===category),[category]);const items=filtered.slice(0,limit);const move=useCallback((direction:number)=>{if(!active)return;const index=filtered.findIndex(x=>x.id===active.id);setActive(filtered[(index+direction+filtered.length)%filtered.length])},[active,filtered]);useEffect(()=>{if(!active)return;const close=(event:KeyboardEvent)=>{if(event.key==='Escape')setActive(null);if(event.key==='ArrowRight')move(1);if(event.key==='ArrowLeft')move(-1)};document.body.style.overflow='hidden';addEventListener('keydown',close);return()=>{document.body.style.overflow='';removeEventListener('keydown',close)}},[active,move]);return <>
 <div className="project-filters no-scrollbar" aria-label="Filter projects">{projectCategories.map(item=><button key={item} className={category===item?'active':''} aria-pressed={category===item} onClick={()=>{setCategory(item);setLimit(12)}}>{item}</button>)}</div>
 <div className="project-masonry">{items.map((item,index)=><article key={item.id} className={`project-tile ${item.featured?'featured':''}`}><button className="media-hover relative block w-full overflow-hidden text-left" onClick={()=>setActive(item)} aria-label={`View ${item.title} project`} >{item.type==='image'?<Image src={item.src} alt={`${item.title}. ${item.description}`} width={1400} height={item.ratio==='portrait'?1750:item.ratio==='landscape'?900:1400} loading={index<4?'eager':'lazy'} className="w-full object-cover" sizes="(min-width:1400px) 25vw,(min-width:768px) 50vw,100vw"/>:<><SmartVideo src={item.src} poster={item.poster} className={`w-full object-cover ${item.ratio==='portrait'?'aspect-[4/5]':'aspect-[16/10]'}`}/><span className="story-play"><Play size={14} fill="currentColor"/> Film</span></>}<span className="media-caption">View project <ArrowUpRight size={14}/></span></button><div className="project-meta"><p>{item.category}</p><h2>{item.title}</h2><span>{item.description}</span></div></article>)}</div>
 {limit<filtered.length&&<div className="load-more"><button onClick={()=>setLimit(v=>v+8)}>Load more work <ArrowRight/></button></div>}
 {active&&createPortal(<div className="lightbox project-dialog" role="dialog" aria-modal="true" aria-label={`${active.title} project detail`}><div className="lightbox-header"><div><p>{active.category}</p><h2>{active.title}</h2></div><button onClick={()=>setActive(null)} aria-label="Close project detail" autoFocus><X/></button></div><div className="project-dialog-layout"><div className="lightbox-stage">{active.type==='image'?<Image src={active.src} alt={active.title} fill className="object-contain" sizes="(min-width:900px) 72vw,100vw" priority/>:<SmartVideo src={active.src} poster={active.poster} className="max-h-full max-w-full"/>}<button className="lightbox-prev" onClick={()=>move(-1)} aria-label="Previous project"><ArrowLeft/></button><button className="lightbox-next" onClick={()=>move(1)} aria-label="Next project"><ArrowRight/></button></div><aside className="project-dialog-copy"><p className="eyebrow">{active.category} project</p><h2>{active.title}</h2><p>{active.description} Woodwey developed the fabrication, furniture, material language and execution as a considered response to the space.</p><Link href="/#contact" onClick={()=>setActive(null)} className="ww-button"><span>Request a similar project</span><i><ArrowUpRight/></i></Link><div className="related-work"><span>Related work</span>{projectMedia.filter(x=>x.category===active.category&&x.id!==active.id).slice(0,2).map(item=><button key={item.id} onClick={()=>setActive(item)}><Image src={item.type==='image'?item.src:item.poster!} alt="" width={120} height={90}/><b>{item.title}</b></button>)}</div></aside></div></div>,document.body)}
 </>}
