import Image from 'next/image'
import Link from 'next/link'
import { ArrowUpRight } from 'lucide-react'
import { projects } from '@/lib/content'
import { Eyebrow, Footer, Header } from '@/components/site-shell'

export const metadata = { title: 'Projects — WOODWEY', description: 'Selected residential, workplace and institutional interiors by WOODWEY.' }

export default function ProjectsPage(){return <main><Header/><section className="px-5 pb-24 pt-36 md:px-10 md:pt-44"><div className="mx-auto max-w-[1600px]"><Eyebrow>Selected projects</Eyebrow><h1 className="max-w-5xl text-balance font-serif text-6xl leading-none md:text-9xl">Made for real rooms. And real life.</h1><p className="mt-8 max-w-lg leading-relaxed text-muted-foreground">A collection of spaces where material, function and atmosphere meet.</p></div></section>{projects.map((p,i)=><section key={p.name} className={`${i%2?'bg-sand':''} px-5 py-16 md:px-10 md:py-24`}><div className={`mx-auto grid max-w-[1600px] gap-7 ${i%2?'md:grid-cols-[1fr_1.6fr]':'md:grid-cols-[1.7fr_1fr]'} md:items-end`}><div className={`relative ${i%2?'md:order-2':''}`}><Image src={p.image} alt={p.alt} width={1800} height={1100} className={`${i%2?'aspect-[4/5]':'aspect-[16/10]'} w-full object-cover`}/><span className="absolute left-4 top-4 bg-background px-3 py-2 text-xs">0{i+1}</span></div><div className={`${i%2?'md:order-1 md:pr-20':'md:pl-14'} pb-4`}><p className="text-xs uppercase tracking-[.2em] text-muted-foreground">{p.location}</p><h2 className="mt-4 font-serif text-4xl md:text-6xl">{p.name}</h2><p className="mt-6 max-w-sm leading-relaxed text-muted-foreground">A considered study in proportion, crafted detail and material warmth—designed around the rhythms of the people who use it.</p></div></div></section>)}<section className="bg-orange px-5 py-24 md:px-10"><div className="mx-auto flex max-w-[1500px] flex-col gap-8 md:flex-row md:items-end md:justify-between"><h2 className="max-w-4xl font-serif text-6xl leading-none md:text-8xl">Your space could be next.</h2><Link href="/#contact" className="flex items-center gap-8 border-b border-ink pb-3">Start a project <ArrowUpRight/></Link></div></section><Footer/></main>}
