'use client'
import Link from 'next/link'
import { useEffect, useState } from 'react'
import { ArrowUpRight, Menu, MessageCircle, X } from 'lucide-react'
const links=[['Home','/'],['Catalog','/catalog'],['Projects','/projects'],['Request a Quote','/#contact']]
export function Header(){const[open,setOpen]=useState(false);const[scrolled,setScrolled]=useState(false);const[count,setCount]=useState(0);useEffect(()=>{const sync=()=>{setScrolled(scrollY>24);try{setCount(JSON.parse(localStorage.getItem('woodwey-selection')||'[]').length)}catch{setCount(0)}};sync();addEventListener('scroll',sync,{passive:true});addEventListener('woodwey-selection',sync);return()=>{removeEventListener('scroll',sync);removeEventListener('woodwey-selection',sync)}},[]);return <header className={`site-header ${scrolled||open?'is-scrolled':''}`}><div className="shell flex h-[68px] items-center justify-between"><Link href="/" aria-label="Woodwey home"><img src="/logos/svg.svg" alt="Woodwey" className="h-12 w-[108px] object-contain object-center" /></Link><nav className="hidden items-center gap-7 md:flex" aria-label="Primary">{links.slice(0,3).map(([l,h])=><Link key={l} href={h}>{l}</Link>)}{count>0&&<Link href="/catalog" className="text-orange">My Selection ({count})</Link>}<Link href="/#contact" className="border border-orange px-4 py-2.5">Request a Quote</Link></nav><button onClick={()=>setOpen(!open)} className="grid size-11 place-items-center md:hidden" aria-expanded={open} aria-label="Toggle menu">{open?<X/>:<Menu/>}</button></div>{open&&<nav className="mobile-menu" aria-label="Mobile">{links.map(([l,h],i)=><Link key={l} href={h} onClick={()=>setOpen(false)}><span>0{i+1}</span>{l}</Link>)}</nav>}</header>}
export function Footer(){return <footer className="relative overflow-hidden bg-ink px-5 py-16 text-ivory md:px-10 md:py-20"><div className="absolute inset-0 bg-[url('/images/IMG-20260813-WA0247.jpg')] bg-cover bg-center opacity-[.07]"/><div className="shell relative"><div className="grid gap-14 border-t border-white/15 pt-10 md:grid-cols-[1.5fr_.7fr_.7fr_1fr]"><div><img src="/logos/svg.svg" alt="Woodwey" className="h-20 w-40 bg-ivory/95 object-contain"/><p className="mt-7 max-w-sm font-serif text-3xl leading-tight">Furniture and interiors shaped around real life.</p><p className="mt-4 text-sm text-ivory/55">Proudly made in Nigeria.</p></div><FooterColumn title="Explore" links={links}/><FooterColumn title="Company" links={[["About",'/#about'],['Contact','/#contact']]}/><div><p className="footer-title">Contact</p><p className="mt-5 text-sm leading-7 text-ivory/70">Lagos, Nigeria<br/><a href="mailto:hello@woodweyng.com">hello@woodweyng.com</a><br/><a href="tel:+2348032973402">+234 803 297 3402</a></p></div></div><div className="mt-16 flex flex-col gap-3 border-t border-white/15 pt-6 text-xs text-ivory/45 md:flex-row md:justify-between"><p>© {new Date().getFullYear()} Woodwey Furniture & Metal Works Ltd.</p><p>Designed and made in Lagos, Nigeria.</p></div></div></footer>}
function FooterColumn({title,links}:{title:string;links:string[][]}){return <div><p className="footer-title">{title}</p><div className="mt-5 flex flex-col gap-3 text-sm text-ivory/70">{links.map(([l,h])=><Link key={l} href={h}>{l}</Link>)}</div></div>}
export function WhatsApp(){return <a className="whatsapp" href="https://wa.me/2348032973402?text=Hello%20Woodwey%2C%20I%20found%20your%20website%20and%20I%27d%20like%20to%20make%20an%20inquiry." target="_blank" rel="noreferrer" aria-label="Chat with Woodwey on WhatsApp"><MessageCircle size={18}/><span>WhatsApp</span></a>}
export function Eyebrow({children}:{children:React.ReactNode}){return <p className="eyebrow">{children}</p>}
export function TextLink({href,children}:{href:string;children:React.ReactNode}){return <Link href={href} className="inline-flex items-center gap-3 border-b border-current pb-2 text-sm">{children}<ArrowUpRight size={16}/></Link>}
